### ISSUE TITLE
FAQ: Why are the values for my regenerated dataset different?

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-docs#99]
Related to: https://github.com/AlexsLemonade/refinebio/issues/1304, https://github.com/AlexsLemonade/refinebio-frontend/issues/633#issuecomment-491928496

@dvenprasad - we might consider adding a tool tip for the regenerate dataset button as well, what do you think?

**Comment by dvenprasad** [comment]
I agree that we should add some sort of indication that user may not receive the same values when they regenerate the files. Maybe an info instead of a tool-tip.

@arielsvn @kurtwheeler 
Ideally, it would be great if we can show this message only when there has been a change in our processing and smash pipelines, so **users won't have to worry about this detail before they have to**. 
Especially our bio expert users.

As an alternate, the message can be visible only if there's been new deploy. (So we won't have to track specific changes to the components(modules?)) 

![Screen Shot 2019-05-14 at 12 06 18 PM](https://user-images.githubusercontent.com/15315514/57713569-b9480480-7640-11e9-8415-adf196de464c.png)

`Learn why` links to the FAQ `Why are the expression values different if I regenerate a dataset?` (which is currently a PR:https://github.com/AlexsLemonade/refinebio-docs/pull/100)

**Comment by kurtwheeler** [comment]
Wait, this got closed but did we want to have a link to the docs in this scenario? That doesn't seem like it was addressed yet....

**Comment by jaclyn-taroni** [comment]
@dvenprasad is going to file a front end ticket
